apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
  labels:
    app: go-web-app
spec:
  template:
    metadata:
      labels: 
        app: go-web-app
    spec:
      containers:
        - name: go-web-app
          image: palaymoundekar/go-web-app:{{.value.tag}}
          ports:
          - containerPort: 8080
  replicas: 2
  selector:
    matchLabels:
      app: go-web-app