name: CI

on: 
   push:
     branches:
       - main 
     paths-ignore:
        - 'heml/**'
        - 'k8s/**'
        - 'README.md'
    
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: action/checkout@v4

    - name: Set up Go 1.22
      uses: actions/setup-go@v4
      with:
        go-version: 1.22

    - name: Test 
      run: go test ./...
      